### ISSUE TITLE
NullReferenceException: SapConnectionPool.ForgetConnection(ISapConnection connection)

### ISSUE THREAD

**Issue by limeless** [huysentruitw/SapNwRfc#13]
Hi,
I've been running my asp.net api with this nuget successfully, both Linux and Windows,
but when deploy on Azure Container Registry, it will throw an NullReferenceException when RFC API being called.
`System.NullReferenceException: Object reference not set to an instance of an object.`
so I pull down the image on azure container and test it inside my WSL, everything is working.

Here is full error that thrown:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SapNwRfc.Pooling.SapConnectionPool.ForgetConnection(ISapConnection connection)
   at SapNwRfc.Pooling.SapPooledConnection.InvokeFunction[TOutput](String name, Object input, CancellationToken cancellationToken)
   at WIP.Repository.SapRFCRepository.QueryStock(RfcParameters query) in /src/WIP.Repository/SapRFCRepository.cs:line 30
   at WIP.Service.SapRFCService.QueryStock(RfcParameters query) in /src/WIP.Service/SapRFCService.cs:line 26
   at WIP.WebAPI.ScheduleController.SAPRFCTEST() in /src/WIP.WebAPI/Controllers/ScheduleController.cs:line 71
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

inside my appsettings.<env>.json I have my ConnectionString to RFC set correctly.

so I'm not quite sure where's the problem is...

Thanks!

**Comment by limeless** [comment]
Ok I got it fixed, 
I feel so stupid because I didn't add my AppService to my SAP's VNET, so it can't gain connection from it.
closing this.

**Comment by panzhangguo** [comment]
> Ok I got it fixed,
> I feel so stupid because I didn't add my AppService to my SAP's VNET, so it can't gain connection from it.
> closing this.

你好，你是怎么解决的？我也碰到了同样的问题。

**Comment by huysentruitw** [comment]
@panzhangguo From what I understand is that the AppService (on Azure) did not have access to the virtual network connecting to the SAP instance. Hence no connections could be resolved and `connection` seems to be `null` in that case.

The library could be improved, so it throws earlier and with a more descriptive exception message.
